apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hiwolleh-source/gitops-test.git
    targetRevision: HEAD
    path: overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
