apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- service.yaml
- rollout.yaml
images:
  - name: ghcr.io/vfarcic/silly-demo:1.4.126
    newTag: 1.4.124  # Updated by CI
